/*
 *  Copyright (c) 2020 Contributors to the Eclipse Foundation
 *
 *  See the NOTICE file(s) distributed with this work for additional
 *  information regarding copyright ownership.
 *
 *  This program and the accompanying materials are made available under the
 *  terms of the Eclipse Public License v. 2.0 which is available at
 *  http://www.eclipse.org/legal/epl-2.0, or the W3C Software Notice and
 *  Document License (2015-05-13) which is available at
 *  https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document.
 *
 *  SPDX-License-Identifier: EPL-2.0 OR W3C-20150513
 */

/**
 * Generate the root level openAPI general information
 * @param {object} td The input TD
 */
function createInfo(td) {
    const cInfo = {};
    // add title
    /* is required for valid TDs but in order to avoid testing constraints,
       TDs are not necessarily validated before OpenAPI generation
       e.g. test upcoming TD spec features */
    if (td.title !== undefined) {
        cInfo.title = td.title;
    } else {
        cInfo.title = "Thing Description Playground autogenerated OpenAPI object";
    }

    // add version
    if (td.version && td.version.instance) {
        cInfo.version = td.version.instance;
    } else {
        cInfo.version = "unknown";
    }

    // add description
    if (td.description !== undefined) {
        cInfo.description = td.description;
    }

    // add support contact
    if (td.support) {
        if (td.support.startsWith("mailto:")) {
            cInfo.contact = { email: td.support.slice(7) };
        } else if (td.support.startsWith("http://") || td.support.startsWith("https://")) {
            cInfo.contact = { url: td.support };
        } else {
            cInfo.contact = { "x-uri": td.support };
        }
    }

    // add optional custom fields
    const tdOpts = ["@context", "@type", "created", "descriptions", "id", "links", "modified", "name", "titles"];
    tdOpts.forEach((prop) => {
        if (td[prop] !== undefined) {
            cInfo["x-" + prop] = td[prop];
        }
    });

    return cInfo;
}

module.exports = createInfo;
