const { Info } = require("./definitions")

/**
 * Generate the root level AsyncAPI general information
 * @param {object} td Input Td
 */
function genInfo(td) {
    const title = (td.title === undefined) ? "Thing Description Playground autogenerated AsyncAPI object" : td.title
    const version = (td.version && td.version.instance) ? td.version.instance : "unknown"

    let contact
    // add support contact
    if (td.support) {
        if (td.support.startsWith("mailto:")) {
            contact = {email: td.support.slice(7)}
        }
        else if (td.support.startsWith("http://") || td.support.startsWith("https://")) {
            contact = {url: td.support}
        }
        else {
            contact = {"x-uri": td.support}
        }
    }

    const info = new Info(title, version, {
        description: td.description,
        contact
    })

    // add optional custom fields
    const tdOpts = ["@context", "@type", "created", "descriptions", "links", "modified", "name", "titles"]
    tdOpts.forEach( prop => {
        if (td[prop] !== undefined) {
            if (prop.startsWith("@")) {
                info["x-AT-" + prop.slice(1)] = td[prop]
            }
            else {
                info["x-" + prop] = td[prop]
            }
        }
    })

    return info
}

module.exports = genInfo