name: Default CI & CD Pipeline

on:
    push:
        paths-ignore:
            - "**.md"
            - "**.png"
            - "**.drawio"
            - "**.xlsx"
    pull_request:
        paths-ignore:
            - "**.md"
            - "**.png"
            - "**.drawio"
            - "**.xlsx"
jobs:
    setup-and-test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x, 20.x]

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm ci

            - name: Test
              run: npm test

            - name: TD test
              run: node packages/cli/index.js -i examples/td/*/*.jsonld

            - name: TM test
              run: node packages/cli/index.js -t TM -i examples/tm/*/*.jsonld
