name: Visual Testing Pipeline

on:
    pull_request:
        paths-ignore:
            - "**.md"
            - "**.png"
            - "**.drawio"
            - "**.xlsx"

jobs:
    setup-and-visual-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Use Node.js 16
              uses: actions/setup-node@v3
              with:
                  node-version: "16.x"

            - name: Use lerna
              run: npm install -g lerna@6.6.2

            - name: Bootstrap
              run: lerna bootstrap --no-ci

            - name: New Web Visual Test
            timeout-minutes: 18
              run: |
                  cd ./packages/web-new
                  npm install
                  npx playwright install
                  npm run test