name: Web-New Visual Testing Pipeline

on:
    pull_request:
        paths-ignore:
            - "**.md"
            - "**.png"
            - "**.drawio"
            - "**.xlsx"

jobs:
    setup-and-visual-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Use Node.js 18
              uses: actions/setup-node@v3
              with:
                  node-version: "18.x"

            - name: Use lerna
              run: npm install -g lerna@6.6.2

            - name: Bootstrap
              run: lerna bootstrap --no-ci
            
            - name: Visual Tests
              timeout-minutes: 18
              run: |
                cd ./packages/web-new
                npm install
                npx playwright install chromium firefox
                npm run build
                npm run serve &
                sleep 10
                npm test

            - uses: actions/upload-artifact@v3
              if: always()
              with:
                name: playwright-report
                path: playwright-report/
                retention-days: 30